export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';

export const RECIPE_IN_PROGRESS = 'RECEPIE_IN_PROGRESS';
export const RECIPE_DONE = 'RECEPIE_DONE';
